FROM python:3.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Corrigido: copiar o requirements.txt do subdiretório correto
COPY backend/requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Copia todo o backend para a imagem
COPY backend .

EXPOSE 8080

CMD ["uvicorn", "mercearia.api.main:app", "--host", "0.0.0.0", "--port", "8080"]
