"""foreign

Revision ID: a04121198496
Revises: ec599f39be04
Create Date: 2025-07-22 00:00:40.586177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04121198496'
down_revision: Union[str, Sequence[str], None] = 'ec599f39be04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favoritos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    # ### end Alembic commands ###
